let projectile: Sprite = null
scene.setBackgroundColor(9)
let mySprite = sprites.create(img`
    ....................
    ....................
    .............77.....
    ..........7777.7....
    ...77....7...7..7...
    ...7.7777....7..7...
    ..7...7.77777...a...
    777...7.77.a...aaa..
    aa....a.7.aaa.aaaaa.
    aaa..aaa7.aaa.aaaaa.
    aaa.aaaaa.a.a.aaaaa.
    a.a.aaaaa.....a.a.a.
    a...aaaaa...........
    ....a.a.a...........
    ........7...........
    ........7...........
    ........7...........
    ....................
    ....................
    ....................
    `, SpriteKind.Player)
game.onUpdateInterval(1000, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . f . . . f . . . . . . . . . 
        . . . f . f . . . . . 9 9 . . . 
        . . . f 5 f 5 f 5 f 9 1 9 f . . 
        . . . 5 5 5 5 f 5 9 1 9 9 f . . 
        . . . f 5 f 5 f 9 1 9 f 5 f f f 
        . . . 5 5 5 5 f 1 9 9 f 5 f . . 
        . . . f f f 5 f 5 f 5 f 5 f . . 
        . . . 5 5 5 5 f 5 f 5 f 5 f . . 
        . . . . . . f . f . f . f . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, mySprite, randint(-25, 25), randint(-25, 25))
    projectile.lifespan = 3000
    if (projectile.vx < 0) {
        projectile.image.flipX()
    }
})
